Evac dispatch map enhancements
trevorskaggs/shelterly pull request #86
Opened 2020-09-26 19:57 UTC by AlexMountain

2020-10-02 19:08 UTC, AlexMountain commented
@trevorskaggs I believe this one is in a good place for a review!  Punting on really polished icons for now, we can circle back with Font Awesome Pro in a later ticket.

2020-10-21 23:45 UTC, trevorskaggs commented on evac/serializers.py
> +    team_member_objects = EvacTeamMemberSerializer(source='team_members', required=False, read_only=True, many=True)
Do we want these to be `required=False`? I cant think of a case where we would want to allow that?

2020-10-22 00:12 UTC, trevorskaggs requested changes
Nice! This is looking really good so far! A lot of really good quality of life improvements tucked in this bad boy.  Really only found a few small issues on the Dispatch Map page:

- [  ]Looks like we might have something wonky happening in the Dispatch map tooltip?
![image](https://user-images.githubusercontent.com/1276123/96802036-d51b1280-13bd-11eb-8a1e-3bfd3415763d.png)
- [  ] Can we stretch the Team Selector object to fill that space up?
![image](https://user-images.githubusercontent.com/1276123/96802069-e8c67900-13bd-11eb-95ae-f70d646ee245.png)
- [  ] Looks like we can have a race condition, if multiple people are deploying Service Requests.  Was able to generate the following: 
![image](https://user-images.githubusercontent.com/1276123/96802611-0ea04d80-13bf-11eb-94cc-35d798796b26.png)
![image](https://user-images.githubusercontent.com/1276123/96802632-15c75b80-13bf-11eb-965b-cded8a93efba.png)
Think this is my bad for not limiting SR FK relationships, but we also dont want to as a SR can be assigned multiple times....  Maybe we just check and dont make the FK, if the SR is already assigned currently?  I can also ticket this separately if that makes more sense!
- [  ] If there are no unassigned SRs, we get this page:
![image](https://user-images.githubusercontent.com/1276123/96802972-e2390100-13bf-11eb-8749-cc82fc1cfaf2.png)
- [  ] On the SR Details page, I am seeing the following in the console:
![image](https://user-images.githubusercontent.com/1276123/96803203-773bfa00-13c0-11eb-8f39-b16a952f187f.png)
This doesnt seem to affect functionality, but could eventually!

2020-10-22 12:20 UTC, AlexMountain commented
@trevorskaggs Couple of things:

We can extend the team field to be the width of the page, but it bumps the DEPLOY button far to the right, kind of disrupting a compact flow.  I've made the change for the time being but we may want to circle on it again.

For some reason I can't seem to reply directly to your comment about the `required` flag, but those flags are specifically for the custom object fields, which we don't want to have to supply on PUT/PATCH/POST requests.  Whether or not the FK itself is required should still be controlled at the model level.

2020-10-22 14:46 UTC, trevorskaggs commented
> For some reason I can't seem to reply directly to your comment about the `required` flag, but those flags are specifically for the custom object fields, which we don't want to have to supply on PUT/PATCH/POST requests. Whether or not the FK itself is required should still be controlled at the model level.

Gotcha! That makes sense!

2020-10-22 17:40 UTC, trevorskaggs approved these changes
All requested changes retested, SEND IT!

2020-10-22 18:08 UTC, merged